import Head from 'next/head'
import styles from '../styles/Home.module.css'
import SignUp from './Components/SignUp'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nsebox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <SignUp />
    </div>
  )
}
